export function blogSandboxPreset(options = {}) {
  return terminal => {
    const fs = terminal.fs;
    const user = options.user || terminal.user;
    const group = options.group || user;
    const blogRoot = options.blogRoot || `/home/${user}/blog`;

    terminal.hostname = options.hostname || terminal.hostname;
    if (!terminal.alias('ll')) terminal.setAlias('ll', 'ls -al');
    if (!terminal.alias('la')) terminal.setAlias('la', 'ls -a');
    if (!terminal.alias('grep')) terminal.setAlias('grep', 'grep --color=auto');

    fs.ensureDir(blogRoot, { owner: user, group });
    fs.addFile(`/home/${user}/.bashrc`, 'alias ll="ls -al"\nalias la="ls -a"\nexport EDITOR=vim\n', { owner: user, group, perm: '-rw-r--r--' });
    fs.addFile(`/home/${user}/.profile`, '[[ -f ~/.bashrc ]] && . ~/.bashrc\n', { owner: user, group, perm: '-rw-r--r--' });
    fs.addFile(`/home/${user}/.bash_history`, 'ls -la\ncat /etc/os-release\njournalctl -n 5\nsudo -l\n', { owner: user, group, perm: '-rw-------' });
    fs.addFile(`${blogRoot}/README.md`, '# Blog workspace\n\nThis directory is generated by the blog-sandbox preset.\n', { owner: user, group });
    fs.addFile(`${blogRoot}/hint.txt`, 'This is a sample hidden file for demos. Replace it with your own content.\n', { owner: user, group, perm: '-rw-r--r--' });

    fs.addFile('/etc/motd', 'Welcome to the Blog Terminal Sandbox.\nAll commands run in an isolated frontend VFS.\n');
    fs.addFile('/etc/hosts', '127.0.0.1 localhost\n127.0.1.1 blog-server\n10.0.2.15 blog-server.internal\n');
    fs.addFile('/var/log/syslog', 'May 08 10:01:01 blog-server systemd[1]: Started static blog service.\nMay 08 10:01:02 blog-server nginx[901]: GET / 200\n');
    fs.addFile('/var/log/auth.log', 'May 08 10:02:01 blog-server sudo: guest : command not allowed ; TTY=pts/0 ; PWD=/home/guest ; USER=root ; COMMAND=/bin/cat /etc/shadow\n', { owner: 'root', group: 'adm', perm: '-rw-r-----' });
    fs.addFile('/root/secret.txt', options.rootSecret || options.rootFlag || 'replace this private demo content\n', { owner: 'root', group: 'root', perm: '-rw-------' });
  };
}
