import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, normalize, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_TERMINAL_CSS } from '../src/index.mjs';

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)));
const dist = join(root, 'dist');

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(join(root, 'src'), join(dist, 'src'), { recursive: true });

writeFileSync(join(dist, 'index.mjs'), "export * from './src/index.mjs';\n");
writeFileSync(join(dist, 'index.d.ts'), "export * from './src/index.mjs';\n");
writeFileSync(join(dist, 'termlet.bundle.mjs'), createBundle());
writeFileSync(join(dist, 'browser-global.bundle.mjs'), createBundle({ exposeGlobal: true }));
writeFileSync(
  join(dist, 'browser-global.mjs'),
  [
    "import * as Termlet from './index.mjs';",
    'globalThis.Termlet = Termlet;',
    "export * from './index.mjs';",
    '',
  ].join('\n'),
);
writeFileSync(join(dist, 'termlet.css'), DEFAULT_TERMINAL_CSS.trim() + '\n');
writeFileSync(
  join(dist, 'README.md'),
  [
    '# Termlet Dist',
    '',
    'This folder is generated by `npm run build`.',
    '',
    'Use `index.mjs` for ES module imports:',
    '',
    '```html',
    '<script type="module">',
    "  import { mountStaticTerminal } from './termlet/index.mjs';",
    '</script>',
    '```',
    '',
    'Use `termlet.bundle.mjs` when you want a single-file ESM bundle for CDN or static hosting.',
    '',
    'Use `browser-global.bundle.mjs` when you want the single-file bundle to expose `globalThis.Termlet`.',
    '',
    '`index.mjs` and `browser-global.mjs` remain source-structured entries for development and debugging.',
    '',
  ].join('\n'),
);

console.log('dist generated');

function createBundle(options = {}) {
  const entry = moduleId(join(root, 'src', 'index.mjs'));
  const modules = new Map();
  collect(entry, modules);
  const entryExports = modules.get(entry).exports;
  const moduleBlocks = [...modules.entries()].map(([id, item]) => (
    `__modules[${JSON.stringify(id)}] = (__exports, __import) => {\n${indent(item.code)}\n};`
  ));
  return [
    '// Generated by scripts/build.mjs. Do not edit by hand.',
    'const __modules = Object.create(null);',
    'const __cache = Object.create(null);',
    ...moduleBlocks,
    'function __import(id) {',
    '  if (__cache[id]) return __cache[id];',
    '  const factory = __modules[id];',
    '  if (!factory) throw new Error(`Termlet bundle missing module: ${id}`);',
    '  const exports = Object.create(null);',
    '  __cache[id] = exports;',
    '  factory(exports, __import);',
    '  return exports;',
    '}',
    `const __entry = __import(${JSON.stringify(entry)});`,
    ...(options.exposeGlobal ? ['globalThis.Termlet = __entry;'] : []),
    ...entryExports.map(name => `export const ${name} = __entry[${JSON.stringify(name)}];`),
    'export default __entry;',
    '',
  ].join('\n');
}

function collect(id, modules) {
  if (modules.has(id)) return;
  const file = join(root, id);
  const source = readFileSync(file, 'utf8').replace(/^\uFEFF/, '');
  const dependencies = new Set();
  const transformed = transformModule(id, source, dependencies);
  modules.set(id, transformed);
  dependencies.forEach(dep => collect(dep, modules));
}

function transformModule(id, source, dependencies) {
  let counter = 0;
  const exports = [];
  const localExports = [];
  let code = source;
  const addExport = (name, local = true) => {
    if (/^[A-Za-z_$][\w$]*$/.test(name) && !exports.includes(name)) exports.push(name);
    if (local && /^[A-Za-z_$][\w$]*$/.test(name) && !localExports.includes(name)) localExports.push(name);
  };
  const resolveImport = specifier => {
    const dep = resolveModule(id, specifier);
    dependencies.add(dep);
    return dep;
  };

  code = code.replace(/import\s*\{([\s\S]*?)\}\s*from\s*['"]([^'"]+)['"];\s*/g, (_, names, specifier) => {
    const dep = resolveImport(specifier);
    return `const { ${formatDestructure(names)} } = __import(${JSON.stringify(dep)});\n`;
  });

  code = code.replace(/export\s*\{([\s\S]*?)\}\s*from\s*['"]([^'"]+)['"];\s*/g, (_, names, specifier) => {
    const dep = resolveImport(specifier);
    const alias = `__reexport${++counter}`;
    const lines = [`const ${alias} = __import(${JSON.stringify(dep)});`];
    parseNames(names).forEach(item => {
      addExport(item.exported, false);
      lines.push(`__exports[${JSON.stringify(item.exported)}] = ${alias}[${JSON.stringify(item.imported)}];`);
    });
    return `${lines.join('\n')}\n`;
  });

  code = code.replace(/export\s+async\s+function\s+([A-Za-z_$][\w$]*)/g, (_, name) => {
    addExport(name);
    return `async function ${name}`;
  });
  code = code.replace(/export\s+function\s+([A-Za-z_$][\w$]*)/g, (_, name) => {
    addExport(name);
    return `function ${name}`;
  });
  code = code.replace(/export\s+class\s+([A-Za-z_$][\w$]*)/g, (_, name) => {
    addExport(name);
    return `class ${name}`;
  });
  code = code.replace(/export\s+(const|let|var)\s+([A-Za-z_$][\w$]*)/g, (_, kind, name) => {
    addExport(name);
    return `${kind} ${name}`;
  });

  code = code.replace(/export\s*\{([\s\S]*?)\};/g, (_, names) => {
    const lines = [];
    parseNames(names).forEach(item => {
      addExport(item.exported);
      lines.push(`__exports[${JSON.stringify(item.exported)}] = ${item.imported};`);
    });
    return lines.join('\n');
  });

  if (localExports.length) {
    code += `\n${localExports.map(name => `__exports[${JSON.stringify(name)}] = ${name};`).join('\n')}\n`;
  }
  return { code, exports };
}

function parseNames(source) {
  return String(source)
    .split(',')
    .map(item => item.trim())
    .filter(Boolean)
    .map(item => {
      const match = item.match(/^([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?$/);
      if (!match) throw new Error(`Unsupported bundle export syntax: ${item}`);
      return { imported: match[1], exported: match[2] || match[1] };
    });
}

function formatDestructure(source) {
  return parseNames(source).map(item => (
    item.imported === item.exported ? item.imported : `${item.imported}: ${item.exported}`
  )).join(', ');
}

function resolveModule(fromId, specifier) {
  if (!specifier.startsWith('.')) throw new Error(`Only relative imports can be bundled: ${specifier}`);
  const fromFile = join(root, fromId);
  const target = resolve(dirname(fromFile), specifier);
  return moduleId(target);
}

function moduleId(file) {
  const normalized = normalize(file.endsWith('.mjs') ? file : `${file}.mjs`);
  return relative(root, normalized).replace(/\\/g, '/');
}

function indent(text) {
  return String(text).split('\n').map(line => `  ${line}`).join('\n');
}
