import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_TERMINAL_CSS } from '../src/index.mjs';

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)));
const dist = join(root, 'dist');

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(join(root, 'src'), join(dist, 'src'), { recursive: true });

writeFileSync(join(dist, 'index.mjs'), "export * from './src/index.mjs';\n");
writeFileSync(
  join(dist, 'browser-global.mjs'),
  [
    "import * as WebTerminalKit from './index.mjs';",
    'globalThis.WebTerminalKit = WebTerminalKit;',
    "export * from './index.mjs';",
    '',
  ].join('\n'),
);
writeFileSync(join(dist, 'web-terminal-kit.css'), DEFAULT_TERMINAL_CSS.trim() + '\n');
writeFileSync(
  join(dist, 'README.md'),
  [
    '# Web Terminal Kit Dist',
    '',
    'This folder is generated by `npm run build`.',
    '',
    'Use `index.mjs` for ES module imports:',
    '',
    '```html',
    '<script type="module">',
    "  import { mountStaticTerminal } from './web-terminal-kit/index.mjs';",
    '</script>',
    '```',
    '',
    'Use `browser-global.mjs` when you want a module script that exposes `globalThis.WebTerminalKit`.',
    '',
  ].join('\n'),
);

console.log('dist generated');
